### ISSUE TITLE
vendor:publish states Nothing to Publish

### ISSUE THREAD

**Issue by mattclements** [rigor789/airbrake-laravel#3]
``` bash
php artisan vendor:publish --provider=rigor789/airbrake-laravel
Nothing to publish.
```

**Comment by rigor789** [comment]
Do you have an airbrake.php in your configs folder? If all fails, just create it manually, and put these in there: https://github.com/rigor789/airbrake-laravel/blob/master/src/config/airbrake.php

**Comment by mattclements** [comment]
Thanks - didn't have airbrake.php in my config folder; just copied manually which works - thanks!

**Comment by adamtester** [comment]
I got the same error, but thanks for the fix
