### ISSUE TITLE
Execptions not pushed to Airbrake

### ISSUE THREAD

**Issue by jahsome** [rigor789/airbrake-laravel#4]
Thanks for your work on this package.

I've installed and configured everything, however no exceptions are being pushed to Airbrake.

I've added my API key, and set the `'enabled'` key to `true` in `config/airbrake.php`, and there are not any ignored exceptions or environments.

I've also registered the service provider in `config/app.php`.

Are there any recommendations for debugging the api calls? I've ensured the correct Handler is being called.

**Comment by jahsome** [comment]
Odd... Immediately after posting this, I started seeing them in Airbrake.

Thanks for your work! Will report any issues if found.

**Comment by rigor789** [comment]
Glad it's working! :+1:
