### ISSUE TITLE
Ignore exception not working

### ISSUE THREAD

**Issue by adamtester** [rigor789/airbrake-laravel#5]
I can't seem to ignore 404 errors, this is what I have:

``` php
  'ignore_exceptions'   => [
    'Symfony\Component\HttpKernel\Exception\NotFoundHttpException',  
    'NotFoundHttpException'
  ],
```

But they still show up in airbrake?

**Comment by rigor789** [comment]
Hey, had a quick look, and I believe airbrake changed their api a little bit. As an alternative, try adding your exceptions to the 

``` PHP
protected $dontReport = [
    HttpException::class,
    ModelNotFoundException::class,
];
```

Inside `app/Exceptions/Handler.php`

And that should skip the airbrake integration completely!

If that doesn't work I'll take a deeper look to find the problem!

**Comment by adamtester** [comment]
Hmm my `$dontReport` already has `HttpException`

``` php
protected $dontReport = [
    HttpException::class,
];
```

I wouldn't mind the 404 errors but I get about 20 a day just from bots trying to hack the site lol

**Comment by rigor789** [comment]
@AdamTester can you please test out the change and see if it resolves your issue?

**Comment by adamtester** [comment]
@rigor789 ok for some reason I can't get it to work, nginx returns a 500 with no errors in any logs when I use the code... I'll keep looking into it.

**Comment by adamtester** [comment]
Ok the problem is this line
`if($this->shouldReport($e)) {`
change it to
`if($this->handler->shouldReport($e)) {`

**Comment by rigor789** [comment]
Sorry, that was a mistake on my part, does the updated code work properly?

**Comment by adamtester** [comment]
It does on my local, I'll try and test on my production at some point today

**Comment by adamtester** [comment]
Tested on production and all working fine! Thanks!
